#!/bin/bash

CURRENT_PATH=${PWD}
RESOURCES=$CURRENT_PATH/resources

MYSQL_DB='scm_cas'
MYSQL_USER='scm'
MYSQL_PASSWORD='123456'

#yum
sed -i '1s/#!\/usr\/bin\/python$/#!\/usr\/bin\/python2.4/' /usr/bin/yum

# Install nginx
cp $RESOURCES/nginx/nginx.repo /etc/yum.repos.d/
yum -y install nginx

# Update nginx config
mv /etc/nginx/nginx.conf  /etc/nginx/nginx.conf.bak
cp $RESOURCES/nginx/nginx.conf /etc/nginx/

# Install mysql
yum -y install mysql-server mysql-devel

# Start mysqld
/etc/init.d/mysqld start

# Mysql initialization
mysql -uroot -e"drop database $MYSQL_DB"
mysql -uroot -e"create database $MYSQL_DB default charset utf8"
mysql -uroot -e"create user $MYSQL_USER@'localhost' identified by '$MYSQL_PASSWORD'"
mysql -uroot -e"grant all privileges on $MYSQL_DB.* to $MYSQL_USER@'localhost'"

# Install Python2.6.6
yum -y install gcc python-devel

cd $RESOURCES/python
tar zxvf Python-2.6.6.tgz
cd  Python-2.6.6
./configure 
make -j2
make install

ln -sf /usr/local/bin/python2.6 /usr/bin/python

# Install pip

cd $RESOURCES/python
tar -zxvf setuptools-0.6c11.tar.gz
cd setuptools-0.6c11/
python setup.py install

cd $RESOURCES/python
tar -zxvf pip-1.0.2.tar.gz
cd  pip-1.0.2
python setup.py install

# Install SCM
cd $RESOURCES/django
tar zxvf scm_0.1.0.tar.gz
cp -r scm /var/www
cd /var/www/scm/requirements
pip install -r prod.txt

# Install uwsgi
yum -y install libxml2-devel

cd $RESOURCES/uwsgi
tar zxvf uwsgi-1.0.1.tar.gz
cd  uwsgi-1.0.1
make -f Makefile.Py26
cp uwsgi /usr/bin/

cp $RESOURCES/uwsgi/django_uwsgi.py /var/www/
cp $RESOURCES/uwsgi/uwsgi.xml /var/www/
cp $RESOURCES/uwsgi/uwsgiserver /etc/init.d/

# Reload nginx config
/etc/init.d/nginx restart

#/etc/init.d/mysqld restart
#yum -y install mysql-server mysql-devel nginx zlib python-devel zlib-devel libxml2 libxml2-devel
#yum -y install gcc gcc-c++ autoconf automake

#make folder 
mkdir -p /var/www/zone_backup 
mkdir -p /var/www/zone_export

